TOKEN_REPRESENTATION_SIZE = 200

PADDING_TOKEN = "#"
BATCH_SIZE = 32
NUM_EPOCHS = 100

MAX_SEQ_LEN = 10
TIME_STEPS = 5
UNKNOWN_TOKEN = "$$$"
ENDLINE_TOKEN = "###"

MAX_VOCAB_SIZE=20000
VALIDATION_SPLIT = 0.2

LOAD_WEIGHTS=True
SAVE_WEIGHTS=False
WEIGHTS_FILE="./models/simple_lstm.h5"

TRAIN=False
